<?php

namespace Database\Seeders;

use App\Models\Annual;
use App\Models\SchoolYear;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AnnualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            /* Pre - School 1 (Play Group & Nursery) */
            [
                'title' => 'Basic Tuition',
                'amount' => 12000,
                'fee_type' => 'Basic Tuition',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 4000,
                'fee_type' => 'Development Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 4500,
                'fee_type' => 'Development Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Manipulatives',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Learning Materials',
                'amount' => 1000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Instructional Materials',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 1,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            /* Pre - School 2 (Kindergarten) */
            [
                'title' => 'Basic Tuition',
                'amount' => 12000,
                'fee_type' => 'Basic Tuition',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 4000,
                'fee_type' => 'Development Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 4500,
                'fee_type' => 'Development Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Manipulatives',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Learning Materials',
                'amount' => 1100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],

            [
                'title' => 'Instructional Materials',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 2,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            /* Pre - School 3 (Preparatory) */
            [
                'title' => 'Basic Tuition',
                'amount' => 12000,
                'fee_type' => 'Basic Tuition',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 4000,
                'fee_type' => 'Development Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 4500,
                'fee_type' => 'Development Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Manipulatives',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Learning Materials',
                'amount' => 1100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Instructional Materials',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 3,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            /* Elementary 1 (Grade 1 - 3) */
            [
                'title' => 'Basic Tuition',
                'amount' => 11000,
                'fee_type' => 'Basic Tuition',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Science Lab Dev Fee',
                'amount' => 1000,
                'fee_type' => 'Development Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Computer Lab Dev Fee',
                'amount' => 1000,
                'fee_type' => 'Development Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 3500,
                'fee_type' => 'Development Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Technology',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 4,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            /* Elementary 1 (Grade 4 - 6) */
            [
                'title' => 'Basic Tuition',
                'amount' => 11500,
                'fee_type' => 'Basic Tuition',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Science Lab Dev Fee',
                'amount' => 1000,
                'fee_type' => 'Development Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Computer Lab Dev Fee',
                'amount' => 1000,
                'fee_type' => 'Development Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 3500,
                'fee_type' => 'Development Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Technology',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 5,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            /* JHS (Grade 7 - 10) */
            [
                'title' => 'Basic Tuition',
                'amount' => 11750,
                'fee_type' => 'Basic Tuition',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Science Lab Dev Fee',
                'amount' => 1500,
                'fee_type' => 'Development Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Computer Lab Dev Fee',
                'amount' => 1500,
                'fee_type' => 'Development Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Digital A/V ITCS',
                'amount' => 2500,
                'fee_type' => 'Development Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Leaning Mgt. System',
                'amount' => 5000,
                'fee_type' => 'Development Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Library (Virtual) Dev',
                'amount' => 3000,
                'fee_type' => 'Development Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Registration Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Processing Fee',
                'amount' => 150,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Permanent Records',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'School ID',
                'amount' => 300,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Class Picture',
                'amount' => 100,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Insurance',
                'amount' => 800,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Technology',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Maintenance & Utilities',
                'amount' => 2000,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
            [
                'title' => 'Student Manual',
                'amount' => 500,
                'fee_type' => 'Miscellaneous Fees',
                'level_id' => 6,
                'sy_id' => SchoolYear::where('is_active', '=', 1)->first()->id,
            ],
        ];
        foreach ($data as $item) {
            Annual::create($item);
        }
    }
}
